[tasks.ben]
description = "Build the project and benchmarks"
script = '''
cargo build
cargo nextest run
cargo criterion --output-format bencher 2>&1 | tee target/bencher.log
python scripts/benchmark_rules.py --input target/bencher.log --rules scripts/benchmark_rules.txt
'''

[tasks.tests]
description = "Run the tests"
script = '''
cargo nextest run --no-fail-fast
'''

[tasks.coverage]
description = "Generates the coverage report"
script = '''
cargo llvm-cov --lcov --output-path target/lcov.info nextest --no-fail-fast
'''

[tasks.precommit]
description = "Run pre-commit checks"
script = '''
cargo llvm-cov --lcov --output-path target/lcov.info nextest
cargo clippy --all-targets --all-features -- -D warnings
cargo fmt --all -- --check
cargo hack check --feature-powerset
codespell --count 0 --skip '*.json'
~/.cargo/bin/zepter run check
git status
'''

[tasks.gitpush]
description = "Push the changes to the remote repository"
dependencies = ["precommit"]
script = '''
git push
'''

[tasks.premerge]
description = "Run pre-merge checks"
dependencies = ["precommit"]
script = '''
sh ./scripts/find_untagged_undones.sh
cargo deny check all
'''

[tasks.docsserver]
description = "Generate documentation and start a local server"
script = '''
cargo doc --workspace --lib --examples --all-features --locked --no-deps
echo "Go ahead and open http://localhost:8000/rods_oram/index.html"
python -m http.server --directory target/doc
'''


[config]
default_to_workspace = false
