[tasks.ben]
description = "Build the project and benchmarks"
script = '''
cargo build
cargo test
cargo criterion --output-format bencher 2>&1 | tee target/bencher.log
python scripts/benchmark_rules.py --input target/bencher.log --rules scripts/benchmark_rules.txt
'''

[tasks.tests]
description = "Run the tests"
script = '''
cargo nextest run
'''

[tasks.precommit]
description = "Run pre-commit checks"
script = '''
cargo test
cargo clippy --all-targets --all-features -- -D warnings
cargo fmt --all -- --check
cargo hack check --feature-powerset
codespell --count 0 --skip '*.json'
~/.cargo/bin/zepter run check
'''

[tasks.gitpush]
description = "Push the changes to the remote repository"
dependencies = ["precommit"]
script = '''
git push
'''

[tasks.premerge]
description = "Run pre-merge checks"
dependencies = ["precommit"]
script = '''
sh ./scripts/find_untagged_undones.sh
cargo deny check all
'''


[config]
default_to_workspace = false