name: bench
on:
  workflow_dispatch:
  merge_group:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Criterion.rs benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Install cargo-binstall
        uses: taiki-e/install-action@cargo-binstall
      - name: Install cargo-criterion
        run: cargo binstall cargo-criterion --force
      - name: Cargo build
        run: cargo build
      - name: Run benchmark
        run: cargo criterion --output-format bencher 2>&1 | tee output.txt
      - name: Store benchmark result
        uses: xtrm0/github-action-benchmark@v1
        with:
          tool: 'cargo'
          output-file-path: output.txt
          # Workflow will fail when an alert happens
          fail-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alert-threshold: '115%'
          # Enable alert commit comment
          comment-on-alert: true
          # Enable Job Summary for PRs
          summary-always: true
          alert-comment-cc-users: '@xtrm0'
          auto-push: true
          benchmark-data-dir-path: 'docs/dev/bench'

